import { useState } from "react";
import { AdminLayout } from "@/components/layout/admin-layout";
import { Input } from "@/components/ui/input";
import { Button } from "@/components/ui/button";
import { Checkbox } from "@/components/ui/checkbox";
import { useListAdminBranches,useUpdateAdminBranch,getListAdminBranchesQueryKey } from "@workspace/api-client-react";
import { useQueryClient } from "@tanstack/react-query";
import { useToast } from "@/hooks/use-toast";
import { Link } from "wouter";
export default function AdminBranches(){const q=useListAdminBranches(); const update=useUpdateAdminBranch(); const qc=useQueryClient(); const {toast}=useToast(); const [editing,setEditing]=useState<number|null>(null);
 return <AdminLayout><div className="p-6 md:p-10 space-y-6 overflow-auto"><h1 className="text-3xl font-bold">Sucursales</h1><p className="text-muted-foreground">Datos operativos y preferencias de notificación.</p><div className="grid gap-4">{q.data?.map(b=><BranchEditor key={b.id} branch={b} editing={editing===b.id} setEditing={setEditing} save={async(data:any)=>{try{await update.mutateAsync({id:b.id,data});await qc.invalidateQueries({queryKey:getListAdminBranchesQueryKey()});toast({title:"Sucursal actualizada"});setEditing(null)}catch{toast({title:"Error al guardar",variant:"destructive"})}}}/>)}</div></div></AdminLayout>}
 function BranchEditor({branch,editing,setEditing,save}:{branch:any;editing:boolean;setEditing:(id:number|null)=>void;save:(d:any)=>Promise<void>}){const [v,setV]=useState<any>({branchCode:branch.branchCode||"",managerName:branch.managerName||"",managerEmail:branch.managerEmail||"",managerPhone:branch.managerPhone||"",notificationPreferences:branch.notificationPreferences||{email:true,whatsapp:false}}); const field=(key:string,label:string)=><label className="text-sm">{label}<Input value={v[key]} onChange={e=>setV({...v,[key]:e.target.value})}/></label>; return <div className="rounded-lg border bg-card p-5 space-y-4"><div className="flex justify-between"><div><Link href={`/admin/sucursales/${branch.id}`}><h2 className="font-semibold hover:text-primary cursor-pointer">{branch.name}</h2></Link><p className="text-xs text-muted-foreground">{branch.address}</p></div>{editing?<Button onClick={()=>save(v)}>Guardar</Button>:<Button variant="outline" onClick={()=>setEditing(branch.id)}>Editar</Button>}</div>{editing&&<><div className="grid gap-3 sm:grid-cols-2">{field("branchCode","Código")}{field("managerName","Responsable")}{field("managerEmail","Email responsable")}{field("managerPhone","Teléfono responsable")}</div><div className="flex gap-6 text-sm"><label className="flex items-center gap-2"><Checkbox checked={!!v.notificationPreferences.email} onCheckedChange={x=>setV({...v,notificationPreferences:{...v.notificationPreferences,email:!!x}})}/> Email</label><label className="flex items-center gap-2"><Checkbox checked={!!v.notificationPreferences.whatsapp} onCheckedChange={x=>setV({...v,notificationPreferences:{...v.notificationPreferences,whatsapp:!!x}})}/> WhatsApp</label></div></>}</div>}